---
Name: event-tickets-discounts
After: 'event-tickets/*'
---
Broarm\EventTickets\ReservationForm:
  extensions:
      - Broarm\EventTickets\AddDiscountExtension
CalendarEvent:
  extensions:
      - Broarm\EventTickets\DiscountEventExtension
