---
Name: event-tickets-discounts
After: 'event-tickets/*'
---
# Broarm\EventTickets\ReservationForm:
#   extensions:
#     - Broarm\EventTickets\Discounts\Extensions\AddDiscountExtension

# YourTicketPageClass:
#   extensions:
#     - Broarm\EventTickets\Discounts\Extensions\DiscountEventExtension
